steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/v135-5213-playground-schalla/Add_user_to_binding', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/v135-5213-playground-schalla/Add_user_to_binding']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'Add_user_to_binding', '--image', 'gcr.io/v135-5213-playground-schalla/Add_user_to_binding','--platform', 'managed', '--region', 'europe-west1']
images:
- gcr.io/v135-5213-playground-schalla/add-user-to-binding